TARGET = hello
CONFIG = apple1

.PHONY: all clean

all: build woz

build: $(TARGET).asm
	cl65 -t none -C ../$(CONFIG).cfg -l $(TARGET).lst -o $(TARGET).prg $(TARGET).asm 
	
view:
	hexdump -C $(TARGET).prg

woz:
	bin2woz -a 0x0300 $(TARGET).prg > $(TARGET).woz

clean:
	rm $(TARGET).prg
	rm $(TARGET).lst
	rm $(TARGET).woz